apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgres-pvc
  namespace: airflow
  labels:
    app: postgres
spec:
  storageClassName: airflow-postgres-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
