apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: airflow
  labels:
    app: postgres
data:
  POSTGRES_DB: airflow_db
  POSTGRES_USER: airflow_user
  POSTGRES_PASSWORD: airflow_pass
